[package]
name = "casper-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
casper-core = { path = "../casper-core" }
ratatui = "0.26.2"
crossterm = "0.27.0"
tokio = { version = "1.46.1", features = ["rt", "net", "io-util"] }
serde_json = "1.0.0"