[package]
name = "casper-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
casper-core = { path = "../casper-core" }
ratatui = "0.23.0"          # TUI framework
crossterm = "0.27.0"       # Terminal handling
tokio = { version = "1.46.1", features = ["rt", "net"] }  # Async runtime